[project]
name = "itsyllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Harshad S", email = "harshad.say@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.0.0",
    "huggingface-hub>=0.30.0",
    "pyarrow>=18.0.0",
    "sentencepiece>=0.2.0",
]
